name: ra-ml
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - lightgbm=2.3.0
  - numpy=1.15
  - pandas=0.23.4
  - pip=18.1
  - scikit-learn=0.20.0
  - scipy=1.1.0
  - hyperopt
  - argparse
